### ISSUE TITLE
Google analytics

### ISSUE THREAD

**Issue by arnodelorme** [sccn/sccn.github.io#57]
Hi Dung,

I have added a new analytics.html file and changed _config.yml but I cannot find the default.html file they are mentioning on this page (https://desiredpersona.com/google-analytics-jekyll/). This is their instructions:

This part may vary depending on what Jekyll theme you are using but you will need to paste the following code just before the end </head> tag. For you this could be a head.html file located in your site's _includes/ directory or your default.html file in _layouts/ directory.

{% if site.google_analytics and jekyll.environment == 'production' %}
{% include analytics.html %}
{% endif %}

Thanks

Arno

**Comment by arnodelorme** [comment]
Hi Arno,

The _layouts folder is hidden for external themes. You can run this command while in the sccn.github.io directory: open $(bundle info --path just-the-docs)

It should open the directory where you can see the default.html file under _layouts.

Dung

**Comment by arnodelorme** [comment]
I was able to open and modify the files, but the modification will be local to me only because not tracked by github. Can we copy the default.html (and head.html) files and modify them on our repository? Will they overwrite the default?

**Comment by dungscout96** [comment]
I copied the default.html into our repository in 4cff867 and it will now be used instead of the default one. Needed to modify it to shorten the just-the-docs credit sentence anyway. You can pull the file and put the Google analytics script in there.
We'll miss any update to this file from the theme developers unless we intentionally check them. But since it's just a layout for the page content, I'm not too worried.

**Comment by dungscout96** [comment]
Added google analytics script to `<head>`

**Comment by dungscout96** [comment]
TODO: retry

**Comment by dungscout96** [comment]
Working now ed46453
